required = ["github.com/golang/protobuf/protoc-gen-go"]

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.18.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "v1.3.2"
