apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: voting-svc
    app.kubernetes.io/name: voting
    app.kubernetes.io/part-of: emojivoto
  name: voting
  namespace: emojivoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-svc
  template:
    metadata:
      labels:
        app: voting-svc
        app.kubernetes.io/name: voting
        app.kubernetes.io/part-of: emojivoto
    spec:
      containers:
      - env:
        - name: GRPC_PORT
          value: "8080"
        - name: PROM_PORT
          value: "8801"
        image: datawire/emojivoto-voting-svc:v11.1
        name: voting-svc
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          requests:
            cpu: 100m
      serviceAccountName: voting
